DEFAULT_CATEGORY_NAME = "sin categoria"

SALE_STATUS_CREDIT = 0
SALE_STATUS_PARTIAL = 1
SALE_STATUS_PAID = 2

PAYMENT_METHOD_CASH = 0
PAYMENT_METHOD_TRANSFER = 1
PAYMENT_METHOD_DEBIT = 2
PAYMENT_METHOD_CREDIT = 3
PAYMENT_METHOD_QR = 4

CASH_MOVEMENT_IN = 0
CASH_MOVEMENT_OUT = 1
